apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: Europe/Madrid
            - name: FTLCONF_dns_listeningMode
              value: "all"
            - name: FTLCONF_dns_upstreams
              value: "1.1.1.1;1.0.0.1"
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: web
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/pihole
          livenessProbe:
            httpGet:
              path: /admin
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /admin
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pihole-config
