apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unidocs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/pabpereza/unidocs:latest
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/ghcr-credentials
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/pabpereza/homelab
    targetRevision: HEAD
    path: kubernetes/unidocs
  destination:
    server: https://kubernetes.default.svc
    namespace: unir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
